FROM centos:centos6

MAINTAINER pabadzhievv@gmail.com

RUN rpm -Uvh http://download.fedoraproject.org

RUN yum install -y npm

COPY ./src

RUN cd /src; npm install

EXPOSE 8080

CMD cd /src && node ./app.js